---
title: "Chlorophyll QC"
output: html_notebook
---

This notebook is being made to start a chlorophyll QC process for new incoming samples. Comparisons will be made for the entire timeseries to look for unusual concentrations.

```{r}
#Upload packages
library(tidyverse)
library(here)
```

```{r}
#Upload chl dataset - entire dataset downloaded from the portal on 2022-01-04
chl <- read_csv(here("files", "chl_2022-01-04.csv"))

#Upload Fluorometer dataset - only qu39 here?

```


```{r}
#Selecting relevant columns
chl <- chl %>% 
  select(date, site_id, line_out_depth, collected, analyzed, hakai_id, 
         calibration, filter_type, before_acid, after_acid, chla, chla_flag, 
         phaeo) 

#Adding month column
chl <- chl %>% 
  mutate(month = lubridate::month(date)) %>% 
  relocate(month, .after = date)

#Checking for duplicates
chl <- chl %>% 
  group_by(collected, site_id, line_out_depth, filter_type) %>% 
  mutate(rep = n()) %>%
  ungroup() %>% 
  mutate(acid_ratio = before_acid/after_acid)

#514 replicated records through the dataset
dup <- chl %>% 
  filter(rep > 1)

#Replicated records for QU39
dup_qu39 <- chl %>% 
  filter(site_id == "QU39" & rep > 1)

```


```{r}
#Turning this off for now.
#Pivoting wider the chlorophyll data to make scatter plots.
# chl_wide <- chl %>% 
#   select(collected, site_id, line_out_depth, rep, filter_type, chla) %>% 
#   pivot_wider(id_cols = c(collected, site_id, line_out_depth),
#               names_from = c(filter_type, rep), 
#               values_from = chla) %>%
#   rename(bulk_chla_1 = `Bulk GF/F_1`,
#          um20_chla_1 = `20um_1`,
#          um3_chla_1 = `3um_1`,
#          GFF_chla_1 = `GF/F_1`) %>% 
#   mutate(sf_sum = um20_chla_1 + um3_chla_1 + GFF_chla_1,
#          diff = bulk_chla_1 - sf_sum)


#Turning this off for now.

#Pivoting Acid Ratio
# ar_wide <- chl_av %>% 
#   select(collected, site_id, line_out_depth, rep, filter_type, acid_ratio) %>% 
#   pivot_wider(id_cols = c(collected, site_id, line_out_depth),
#               names_from = c(filter_type, rep), 
#               values_from = acid_ratio) %>% 
#   rename(ar_bulk = `Bulk GF/F_1`,
#          ar_20  = `20um_1`,
#          ar_3um = `3um_1`,
#          ar_gff = `GF/F_1`)

#Turning this off for now.

#Joining Chla and Acid Ratios
# chl_wide <- chl_wide %>% 
#   left_join(ar_wide, by = c("collected", "site_id", "line_out_depth"))
```

```{r}
#Looking at QU39 and making a time-series plot of bulk chl concentrations separated by depth and colored by flag

chl %>%
  filter(site_id == "QU39" & line_out_depth < 50 &
           filter_type == "Bulk GF/F") %>% 
  ggplot(aes(x = date, y = chla)) + 
  geom_point(aes(fill = chla_flag), pch = 21, size = 3) + 
  geom_line() + 
  facet_grid(line_out_depth ~ ., scales = "free_y") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"))

ggsave(here("figures_qc", "QC_bulk_qu39_depth_TS.png"), 
       width = 16, height = 12, dpi=300)
```
```{r}
#Looking at QU39 and making a time-series plot of bulk chl concentrations without a flag

chl %>%
  filter(site_id == "QU39" & line_out_depth < 50 &
           filter_type == "Bulk GF/F" & is.na(chla_flag)) %>% 
  ggplot(aes(x = date, y = chla)) + 
  geom_point(pch = 21, size = 3, fill = "gray") + 
  geom_line() + 
  facet_grid(line_out_depth ~ ., scales = "free_y") +
  theme_bw() +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"))

ggsave(here("figures_qc", "QC_bulk_qu39_depth_TS_no_flag.png"), 
       width = 16, height = 12, dpi=300)
```
```{r}
# I could make a box and whisker plot to of monthly data to show if any points fall outside of the expected range
chl %>%
  filter(site_id == "QU39" & line_out_depth < 50 &
           filter_type == "Bulk GF/F") %>% 
  ggplot(aes(x = as.factor(month), y = log10(chla + 1))) + 
  geom_boxplot() +
  # geom_dotplot(aes(fill = chla_flag), color = "black", trim = FALSE, binaxis = 'y', 
  #              stackdir ='center', dotsize = 2) +
  geom_jitter(aes(fill = chla_flag), pch = 21, size = 3, color = "black", 
              alpha = 0.8, 
              position=position_jitter(0.2)) +
  facet_grid(line_out_depth ~ ., scales = "free_y") +
  theme_bw() 

ggsave(here("figures_qc", "QC_bulk_qu39_depth_box.png"), 
       width = 16, height = 12, dpi=300)
```

```{r}
#Size fractionated sum versus Bulk
#Fluorometer versus Bulk
#HPLC versus Bulk
```

```{r}
#Pulling out qu39 data
qu39 <- chl %>% 
  filter(site_id == "QU39")

#Pulling out QU39 size-fractionated data
qu39_sf <- qu39 %>% 
  filter(!filter_type == "Bulk GF/F")

#Looking at number of filters for each size fraction
qu39_sf <- qu39_sf %>% 
  group_by(collected, line_out_depth) %>% 
  mutate(filt_num = n()) %>% 
  ungroup()

#Looking for size fraction sets that have less than 3 filters -  this should be investigated to see what these have less then three filters in the set. I haven't applied any flags or removed records with no data, so these would be missing records?
qu39_filt_check_low <- qu39_sf %>% 
  filter(filt_num < 3)

#Looking at size fraction sets that have more than 4 filters. It also shows if a filter size has been replicated.
qu39_filt_check_high <- qu39_sf %>% 
  filter(filt_num > 3)

#Subsetting where there are 3 size-fractionated filters (as there should be). This misses where there may be 2 duplicated filter types and one filter type missing. Do I account for this later?
qu39_sf <- qu39_sf %>% 
  filter(filt_num == 3)

#This find and isolates where a filter type has been replicated (and likely one is missing as there are 3 filters total) - Doesn't seem to be catching everything. Cross checked with my excel list.
qu39_dup_filt <- qu39_sf %>% 
  group_by(collected, line_out_depth, filter_type) %>% 
  mutate(filt_unique = n()) %>% 
  ungroup() %>% 
  filter(filt_unique > 1)

#This filters for where there are 3 filters with no duplicated filter types.
qu39_sf <- qu39_sf %>% 
  group_by(collected, line_out_depth, filter_type) %>% 
  mutate(filt_unique = n()) %>% 
  ungroup() %>% 
  filter(filt_unique == 1)

#Calculating the size fractionated sum for comparison with the bulk data
qu39_sf_sum <- qu39_sf %>% 
  group_by(collected, line_out_depth) %>% 
  mutate(sf_sum = sum(chla)) %>% 
  ungroup() %>% 
  distinct(collected, line_out_depth, sf_sum, .keep_all = TRUE) %>% 
  select(collected, line_out_depth, sf_sum)
```


```{r}
#Working with the bulk data

#Pulling out the bulk filters
qu39_bulk <- qu39 %>% 
  filter(filter_type == "Bulk GF/F")

#Adding a row showing duplicates for each collection time and depth
qu39_bulk <- qu39_bulk %>% 
  group_by(collected, line_out_depth) %>% 
  mutate(filt_num = n()) %>% 
  ungroup()

#Looking at duplicated samples -  24 records. One true and the rest are from when we sent samples to DFO for comparison. The DFO data includes the DFO data, which wasn't analyzed by us, but also a black row for each depth that must be a portal error.
qu39_bulk_check <- qu39_bulk %>% 
  filter(filt_num > 1)

#Just pulling out records without any duplicates
qu39_bulk <- qu39_bulk %>% 
  filter(filt_num == 1)

#Merging with the size-fractionated data for comparison.
qu39_compare <- qu39_bulk %>% 
  left_join(qu39_sf_sum)

```

```{r}
#Some issues here with data that is SVC but should likely be SVD. Notably for bulk samples.

qu39_compare %>% 
  ggplot(aes(x = chla, y = sf_sum, fill = chla_flag)) + 
  geom_point(pch = 21) +
  theme_bw()
```

```{r}
#Looking at QU39 20um TS

chl %>%
  filter(site_id == "QU39" & line_out_depth < 101 &
           filter_type == "20um") %>% 
  ggplot(aes(x = date, y = chla)) + 
  geom_point(aes(fill = chla_flag), pch = 21, size = 3) + 
  geom_line() + 
  facet_grid(line_out_depth ~ ., scales = "free_y") +
  theme(text = element_text(size = 25),
        axis.text = element_text(colour = "black"))

ggsave(here("figures_qc", "QC_20um_qu39_depth_TS.png"), 
       width = 16, height = 12, dpi=300)
```



```{r}
#How many qu39 samples are there for each flag?
flags_qu39 <- chl %>% 
  filter(site_id == "QU39") %>% 
  group_by(filter_type, chla_flag) %>% 
  summarise(n = n()) %>%  
  ungroup()

```

