---
title: "2021 Chlorophyll Data Assessment"
output: html_notebook
---

This workbook quanitifies how many samples were collected in 2021 - at which stations, depths and groups.

```{r}
#Load packages
library(tidyverse)  
library(readxl)
library(here)
library(patchwork)
```

```{r}
#Read data file downloaded from the portal - downloaded on 2021-10-06, so in this version does not include entire year
chl <- read_csv(here("files", "chl_2021-11-02.csv"))


```

```{r}
#Limiting to pertinent columns
chl <- chl %>% 
  select(date, work_area, survey, site_id, line_out_depth, filter_type, chla)

chl <- chl %>% 
  mutate(year = lubridate::year(date))

```

```{r}
#Creating some summary lists to see what stations are being collected by each group

#Making a list of distinct stations and surveys
stations <- chl %>% 
  distinct(site_id)

#Making a list of distinct surveys
surveys <- chl %>% 
  distinct(survey)

#Making a list of distinct survey/stations matches
stations_survey <- chl %>% 
  distinct(survey, site_id)
```

```{r}
#Classifying stations/surveys by group that collected them - trying it first on the truncated list
chl <- chl %>%
  mutate(group = NA) %>% 
  mutate(group = case_when(survey == "MACRO_MGEO" | survey == "ROCKY" ~ "NS",
                           survey == "ZOOPSPRINT" ~ "MFW",
                           survey == "BIOWEEKLY" ~ "Bio.",
                           survey == "TOBA" ~ "Toba",
                           survey == "QOMA1" ~ "Ocean",
                           survey == "QOMA5" ~ "Ocean",
                           survey == "QCS_V1" ~ "Ocean",
                           survey == "KWAK" ~ "Ocean", 
                           survey == "RVRS" ~ "Ocean",
                           survey == "BIOTIDAL" ~ "Bio.",
                           survey == "BUTE" ~ "Bute",
                           survey == "FZH,KWAK" ~ "Ocean",
                           survey == "JS1" ~ "JS",
                           survey == "JS12" ~ "JS",
                           survey == "KNIGHT" ~ "Kni.",
                           survey == "KWAK,FZH" ~ "Ocean",
                           survey == "MFW" ~ "MFW",
                           survey == "QCS_V2" ~ "Ocean",
                           survey == "QOMD" ~ "Ocean",
                           survey == "QOME" ~ "Ocean",
                           survey == "QRAFT" ~ "Ocean",
                           survey == "QRAFT1" ~ "Ocean",
                           survey == "QRAFTB" ~ "Ocean",
                           survey == "SEASTAR WASTING DISEASE,ROCKY" ~ "NS",
                           TRUE ~ as.character(group)))

#Looking at what surveys I'm missing by adding 2019 and 2020 data
na <- chl %>% 
  filter(is.na(group)) %>% 
  distinct(survey, site_id)

```

```{r}
#Order filter types for plotting
order <- c("20um", "3um", "GF/F", "Bulk GF/F")

#Chemtax - Specify order of phyto groups for figures
chl <- arrange(mutate(chl, filter_type = factor(filter_type,
                                levels = order)))
```

```{r}
#Calculating total number of samples per group
totals_2019 <- chl %>% 
  filter(year == 2019) %>% 
  group_by(group) %>%
  summarize(n_tot = n()) %>% 
  ungroup()

totals_2020 <- chl %>% 
  filter(year == 2020) %>% 
  group_by(group) %>%
  summarize(n_tot = n()) %>% 
  ungroup()

totals_2021 <- chl %>% 
  filter(year == 2021) %>% 
  group_by(group) %>%
  summarize(n_tot = n()) %>% 
  ungroup()
```


```{r}
#Plotting number of samples per group - stacked by filter type

chl_2019 <- chl %>% 
  filter(year == 2019 & !is.na(filter_type)) %>% 
  group_by(group, filter_type) %>% 
  summarise(n_filt = n()) %>% 
  ungroup()  
  
#Order filter types for plotting
order_2019 <- c("MFW", "Toba", "Kni.", "Bute", "NS", "JS", "Ocean")

#Chemtax - Specify order of phyto groups for figures
chl_2019 <- arrange(mutate(chl_2019, group = factor(group,
                                levels = order_2019)))

p1 <- chl_2019 %>% 
  ggplot(aes(x = group, y = n_filt, fill = filter_type)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(x = group, y = n_tot, label = n_tot, fill = NULL),
              data = totals_2019, vjust = -0.5) +
  ggsci::scale_fill_npg(name = "Filter Size") +
  ylim(0, 2200) +
  ylab("# of samples") +
  ggtitle(2019) +
  theme_bw() +
  theme(legend.position = c(0.2, 0.8),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        text = element_text(size = 25))

p2 <- chl %>% 
  filter(year == 2020 & !is.na(filter_type)) %>% 
  group_by(filter_type, group) %>% 
  summarise(n_filt = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(group, n_filt), y = n_filt, fill = filter_type)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(x = group, y = n_tot, label = n_tot, fill = NULL),
              data = totals_2020, vjust = -0.5) +
  ggsci::scale_fill_npg(name = "Filter Size") +
  ylim(0, 2200) +
  ylab("# of samples") +
  ggtitle(2020) +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        text = element_text(size = 25))

p3 <- chl %>% 
  filter(year == 2021 & !is.na(filter_type)) %>% 
  group_by(filter_type, group) %>% 
  summarise(n_filt = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(group, n_filt), y = n_filt, fill = filter_type)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(x = group, y = n_tot, label = n_tot, fill = NULL),
              data = totals_2021, vjust = -0.5) +
  ggsci::scale_fill_npg(name = "Filter Size") +
  ylim(0, 2200) +
  ylab("# of samples") +
  ggtitle(2021) +
  theme_bw() +
  theme(legend.position = "none",
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        text = element_text(size = 25))

fig <- p1 + p2 + p3

ggsave(here("figures", "sample_numbers_by_group.png"), fig,
       width = 16, height = 6, dpi = 300)

```


```{r}
#Plotting number of samples per group - stacked by filter type

f1 <- chl %>% 
  filter(group == "nearshore") %>% 
  group_by(filter_type, site_id) %>% 
  summarise(n_filt = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(site_id, n_filt), y = n_filt, fill = filter_type)) +
  geom_bar(stat = "identity", color = "black") +
  # geom_text(aes(x = site_id, y = n_tot, label = n_tot, fill = NULL)
  #           , vjust = -0.5) +
  ggsci::scale_fill_npg(name = "Filter Size") +
  ylim(0, 25) +
  ylab("# of samples") +
  theme_bw() +
  theme(legend.position = c(0.12, 0.8),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 25))

f2 <- chl %>% 
  filter(group == "nearshore") %>% 
  group_by(line_out_depth, site_id) %>% 
  summarise(n_dep = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(site_id, n_dep), y = n_dep, 
             fill = as.factor(line_out_depth))) +
  geom_bar(stat = "identity", color = "black") +
  # geom_text(aes(x = site_id, y = n_tot, label = n_tot, fill = NULL)
  #           , vjust = -0.5) +
  ggsci::scale_fill_npg(name = "Depth") +
  ylim(0, 25) +
  ylab("# of samples") +
  theme_bw() +
  theme(legend.position = c(0.07, 0.7),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.4),
        text = element_text(size = 25))

fig <- f1/f2

ggsave(here("figures", "sample_numbers_nearshore.png"), fig,
       width = 11, height = 12, dpi = 300)
```


```{r}
f1 <- chl %>% 
  filter(group == "foodwebs" | group == "biomarathon" | group == "toba") %>% 
  group_by(filter_type, site_id) %>% 
  summarise(n_filt = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(site_id, n_filt), y = n_filt, fill = filter_type)) +
  geom_bar(stat = "identity", color = "black") +
  # geom_text(aes(x = site_id, y = n_tot, label = n_tot, fill = NULL)
  #           , vjust = -0.5) +
  ggsci::scale_fill_npg(name = "Filter Size") +
  # ylim(0, 25) +
  ylab("# of samples") +
  theme_bw() +
  theme(legend.position = c(0.08, 0.81),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 25))

f2 <- chl %>% 
  filter(group == "foodwebs" | group == "biomarathon" | group == "toba") %>% 
  group_by(line_out_depth, site_id) %>% 
  summarise(n_dep = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(site_id, n_dep), y = n_dep, 
             fill = as.factor(line_out_depth))) +
  geom_bar(stat = "identity", color = "black") +
  # geom_text(aes(x = site_id, y = n_tot, label = n_tot, fill = NULL)
  #           , vjust = -0.5) +
  ggsci::scale_fill_npg(name = "Depth") +
  # ylim(0, 25) +
  ylab("# of samples") +
  theme_bw() +
  theme(legend.position = c(0.05, 0.79),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.4),
        text = element_text(size = 25))

fig <- f1/f2

ggsave(here("figures", "sample_numbers_food-bio-toba.png"), fig,
       width = 13, height = 12, dpi = 300)
```
```{r}
f1 <- chl %>% 
  filter(group == "oceanography") %>% 
  group_by(filter_type, site_id) %>% 
  summarise(n_filt = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(site_id, n_filt), y = n_filt, fill = filter_type)) +
  geom_bar(stat = "identity", color = "black") +
  # geom_text(aes(x = site_id, y = n_tot, label = n_tot, fill = NULL)
  #           , vjust = -0.5) +
  ggsci::scale_fill_npg(name = "Filter Size") +
  # ylim(0, 25) +
  ylab("# of samples") +
  theme_bw() +
  theme(legend.position = c(0.08, 0.81),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 25))

f2 <- chl %>% 
  filter(group == "oceanography") %>% 
  group_by(line_out_depth, site_id) %>% 
  summarise(n_dep = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(site_id, n_dep), y = n_dep, 
             fill = as.factor(line_out_depth))) +
  geom_bar(stat = "identity", color = "black") +
  # geom_text(aes(x = site_id, y = n_tot, label = n_tot, fill = NULL)
  #           , vjust = -0.5) +
  ggsci::scale_fill_npg(name = "Depth") +
  # ylim(0, 25) +
  ylab("# of samples") +
  theme_bw() +
  theme(legend.position = c(0.05, 0.65),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.4),
        text = element_text(size = 25))

fig <- f1/f2

ggsave(here("figures", "sample_numbers_ocean.png"), fig,
       width = 13, height = 12, dpi = 300)
```

```{r}
#So, can we reduce the depths we are collecting size fractionated chlorophyll???

#Crossed checked for duplicates and didn't find any.

qu39 <- chl %>% 
  filter(group == "oceanography" & site_id == "QU39" & !filter_type == "Bulk GF/F") %>%
  group_by(date, line_out_depth) %>% 
  mutate(sum_chl = sum(chla)) %>% 
  ungroup() %>% 
  mutate(perc = chla/sum_chl)

qu39 %>% 
  filter(filter_type == "20um") %>% 
  ggplot(aes(x = date, y = perc, color = as.factor(line_out_depth))) +
  geom_line()
  







```

