---
title: "R Notebook"
output: html_notebook
---

```{r}
#Load packages
library(tidyverse)  
library(readxl)
library(here)
library(patchwork)
library(ggcorrplot)
library(vegan)
library(ggpubr)
```

```{r}
#Read data file downloaded from the portal - This is the full timeseries of QU39 and KC10 data
c <- read_csv(here("files", "2024-03-25_HakaiData_chlorophyll.csv"))

#I want to look at all chlorophyll data collected in 2023
c_23_all <- read_csv(here("files", "2024-03-26_HakaiData_chlorophyll.csv"))

#I should pronna
```

```{r}
#Limiting to pertinent columns
c <- c %>% 
  select(date, collected, work_area, survey, site_id, line_out_depth,
         filter_type, chla, chla_flag)

c_23_all <- c_23_all %>% 
  select(date, collected, work_area, survey, site_id, line_out_depth,
         filter_type, chla, chla_flag)

#Adding year column
c <- c %>% 
  mutate(year = lubridate::year(date))

#Only including AV and unflagged data
c_qc <- c %>% 
  filter(!is.na(chla) & (chla_flag == "AV" | chla_flag == "ADL" | is.na(chla_flag)))

#Removing exact duplicates -  not replicates. Not sure why these are happening
c_qc <- c_qc %>% 
  group_by(date, site_id, line_out_depth, filter_type) %>% 
  distinct(.keep_all = TRUE) %>% 
  ungroup()

#Calculating daily mean where there are replicates - OK for now, but should try to cut out non-ocean samples if just doing 
c_dm <- c_qc %>% 
  filter(chla > 0) %>% 
  group_by(date, site_id, line_out_depth, filter_type) %>% 
  summarise(chla_dm = mean(chla),
            chla_sdev = sd(chla),
            n_samp = n()) %>% 
  ungroup() %>% 
  mutate_at(vars(chla_dm, chla_sdev), funs(round(., 2)))

#Separating Bulk data
c_bulk <- c_dm %>% 
  filter(filter_type == "Bulk GF/F")

#Separting size-fractionated data and calculating size-fractionated sum
c_sf <- c_dm %>% 
  filter(!filter_type == "Bulk GF/F") %>% 
  group_by(date, site_id, line_out_depth) %>% 
  mutate(n_filt = n()) %>% 
  ungroup() %>% 
  group_by(date, site_id, line_out_depth, filter_type) %>%
  mutate(n_type = n()) %>% 
  ungroup() %>% 
  filter(n_filt == 3 & n_type == 1) %>% 
  group_by(date, site_id, line_out_depth) %>% 
  mutate(sf_sum = sum(chla_dm)) %>% 
  ungroup() %>% 
  mutate(sf_perc = chla_dm/sf_sum) %>% 
  group_by(date, site_id, line_out_depth) %>% 
  mutate(perc_check = sum(sf_perc)) %>% 
  ungroup()

c_sf_perc_wide <- c_sf %>%
  filter(!filter_type == "2um") %>% 
  select(date, site_id, line_out_depth, filter_type, sf_perc) %>% 
  pivot_wider(names_from = filter_type, values_from = sf_perc) %>% 
  drop_na()
  
```

```{r}
#Creating some summary lists to see what stations are being collected by each group

#Making a list of distinct stations and surveys
stations <- c_23_all %>% 
  distinct(site_id)

#Making a list of distinct surveys
surveys <- c_23_all %>% 
  distinct(survey)

#Making a list of distinct survey/stations matches
stations_survey <- c_23_all %>% 
  distinct(survey, site_id)
```

```{r}
#Order filter types for plotting
order <- c("20um", "3um", "GF/F", "Bulk GF/F")

#Chemtax - Specify order of phyto groups for figures
c_23_all <- arrange(mutate(c_23_all, filter_type = factor(filter_type,
                                levels = order)))
```

```{r}
test <- c_23_all %>% 
  filter(survey == "FJORDS_BIODIVERSITY")
```

```{r}
#Classifying stations/surveys by group that collected them - trying it first on the truncated list
c_23_all <- c_23_all %>%
  mutate(group = NA) %>% 
  mutate(group = case_when(survey == "QOMA1" | survey == "QOMA5" ~ "Quadra OCGY",
                           survey == "RVRS" | survey == "KWAK" ~ "Calvert OCGY",
                           survey == "BIOWEEKLY" ~ "Quadra Biodiversity",
                           survey == "ROCKY" | survey == "MACRO_MGEO" ~ "Calvert Nearshore",
                           survey == "RVRS;FJORDS_BIODIVERSITY" |
                             survey == "FJORDS_BIODIVERSITY" ~ "UBC Fjords Biodiversity",
                           TRUE ~ as.character(group)))

#Looking at what surveys I'm missing by adding 2019 and 2020 data
na <- c_23_all %>% 
  filter(is.na(group)) %>% 
  distinct(survey, site_id)

```


```{r}
chl_2023_group <- c_23_all %>% 
  filter(!is.na(filter_type)) %>% 
  group_by(group, filter_type) %>% 
  summarise(n_filt = n()) %>% 
  ungroup() 

chl_2023_group <- arrange(mutate(chl_2023_group, filter_type = factor(filter_type,
                                levels = order)))

#Calculating total number of samples per group
totals_2023 <- c_23_all %>% 
  group_by(group) %>%
  summarize(n_tot = n()) %>% 
  ungroup()


chl_2023_group %>% 
  ggplot(aes(x = reorder(group, n_filt), y = n_filt, fill = filter_type)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(x = group, y = n_tot, label = n_tot, fill = NULL),
              data = totals_2023, vjust = -0.5, size = 12) +
  # facet_wrap(~survey, scales = "free") +
  ggsci::scale_fill_npg(name = "Filter Size") +
  ylim(0, 1200) +
  ylab("# of samples") +
  ggtitle(2023) +
  theme_bw() +
  theme(legend.position = c(0.1, 0.8),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(color = "black"),
        text = element_text(size = 35, 
                            color = "black"))

ggsave(here("figs_invent", "sample_numbers_group_2023.png"), 
       width = 16, height = 10, dpi = 300)
```

```{r}
chl_2023_calvert <- c_23_all %>% 
  filter(group == "Calvert OCGY" ) %>%
  filter(!is.na(filter_type)) %>% 
  group_by(site_id, filter_type) %>% 
  summarise(n_filt = n()) %>% 
  ungroup() 

chl_2023_calvert <- arrange(mutate(chl_2023_calvert, filter_type = factor(filter_type,
                                levels = order)))

#Calculating total number of samples per group
totals_2023_calvert <- c_23_all %>%
  filter(group == "Calvert OCGY" ) %>%
  group_by(site_id) %>%
  summarize(n_tot = n()) %>% 
  ungroup()


chl_2023_calvert %>% 
  ggplot(aes(x = reorder(site_id, n_filt), y = n_filt, fill = filter_type)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(x = site_id, y = n_tot, label = n_tot, fill = NULL),
              data = totals_2023_calvert, vjust = -0.5, size = 8) +
  ylim(0, 300) +
  ggsci::scale_fill_npg(name = "Filter Size") +
  ylab("# of samples") +
  ggtitle(2023) +
  theme_bw() +
  theme(legend.position = c(0.13, 0.8),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        axis.text = element_text(color = "black"),
        text = element_text(size = 25, 
                            color = "black"))

ggsave(here("figs_invent", "sample_numbers_calvert_2023_2.png"), 
       width = 8, height = 6, dpi = 300)
```



```{r}
#Looking at what sampling depth usually had the peak in chlorophyll biomass.
c_max <- c_bulk %>% 
  filter(line_out_depth < 50) %>% 
  group_by(date, site_id) %>% 
  slice_max(chla_dm) %>% 
  ungroup()

#Summarizing the number of times each depth was the max depth for each station
c_max_n <- c_max %>% 
  group_by(site_id, line_out_depth) %>% 
  summarise(n_max = n()) %>% 
  ungroup() %>% 
  group_by(site_id) %>% 
  mutate(sum = sum(n_max)) %>% 
  ungroup() %>% 
  mutate(max_perc = n_max/sum*100) %>% 
  mutate_at(vars(max_perc), funs(round(., 0)))
```

```{r}
cq_20 <- c_sf %>% 
  filter(site_id == "QU39" & filter_type == "20um" & line_out_depth < 31) %>% 
  select(date, line_out_depth, sf_perc) %>%
  pivot_wider(names_from = line_out_depth, values_from = sf_perc) %>% 
  select(`0m` = `0`, `5m` = `5`, `10m` = `10`, `20m` = `20`, `30m` = `30`) %>% 
  drop_na()

corr_q_20 <- round(cor(cq_20), 1)

p.mat_q_20 <- cor_pmat(cq_20)

head(p.mat_q_20[, 1:5])

f1 <- ggcorrplot(corr_q_20,
           outline.color = "white",
           lab = TRUE,
           insig = "blank",
           type = "lower", 
           p.mat = p.mat_q_20,
           lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0, 1), low = "white", 
                      high =  "Red") +
  ggtitle("% Micro") +
  annotate("text", x = 1, y = 4.3, label = "QU39", size = 10) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text = element_text(color = "black"),
        legend.position = c(0.15, 0.68),
        text = element_text(size = 35))
```


```{r}
cq_3 <- c_sf %>% 
  filter(site_id == "QU39" & filter_type == "3um" & line_out_depth < 31) %>% 
  select(date, line_out_depth, sf_perc) %>%
  pivot_wider(names_from = line_out_depth, values_from = sf_perc) %>% 
  select(`0m` = `0`, `5m` = `5`, `10m` = `10`, `20m` = `20`, `30m` = `30`) %>% 
  drop_na()

corr_q_3 <- round(cor(cq_3), 1)

p.mat_q_3 <- cor_pmat(cq_3)
head(p.mat_q_3[, 1:5])

f2 <- ggcorrplot(corr_q_3, 
           outline.color = "white",
           lab = TRUE,
           insig = "blank",
           type = "lower", 
           p.mat = p.mat_q_3,
           lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0, 1), low = "white", 
                      high =  "Red") +
  ggtitle("% Nano") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(color = "black"),
        legend.position = "none",
        text = element_text(size = 35))
```


```{r}
f3 <- cq_g <- c_sf %>% 
  filter(site_id == "QU39" & filter_type == "GF/F" & line_out_depth < 31) %>% 
  select(date, line_out_depth, sf_perc) %>%
  pivot_wider(names_from = line_out_depth, values_from = sf_perc) %>% 
  select(`0m` = `0`, `5m` = `5`, `10m` = `10`, `20m` = `20`, `30m` = `30`) %>% 
  drop_na()

corr_q_g <- round(cor(cq_g), 1)

p.mat_q_g <- cor_pmat(cq_g)
head(p.mat_q_g[, 1:5])

f3 <- ggcorrplot(corr_q_g,
           outline.color = "white",
           lab = TRUE,
           insig = "blank",
           type = "lower", 
           p.mat = p.mat_q_g,
           lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0, 1), low = "white", 
                      high =  "Red") +
  ggtitle("% Pico") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(color = "black"),
        legend.position = "none",
        text = element_text(size = 35))
```


```{r}
ck_20 <- c_sf %>% 
  filter(site_id == "KC10" & filter_type == "20um" & line_out_depth < 31) %>% 
  select(date, line_out_depth, sf_perc) %>%
  pivot_wider(names_from = line_out_depth, values_from = sf_perc) %>% 
  select(`0m` = `0`, `5m` = `5`, `10m` = `10`, `20m` = `20`, `30m` = `30`) %>% 
  drop_na()

corr_k_20 <- round(cor(ck_20), 1)

p.mat_k_20 <- cor_pmat(ck_20)
head(p.mat_k_20[, 1:5])

f4 <- ggcorrplot(corr_k_20,
                 outline.color = "white",
           lab = TRUE,
           insig = "blank",
           type = "lower", 
           p.mat = p.mat_k_20,
           lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0, 1), low = "white", 
                      high =  "Red") +
  annotate("text", x = 1, y = 4.3, label = "KC10", size = 10) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(color = "black"),
        legend.position = "none",
        text = element_text(size = 35))
```


```{r}
ck_3 <- c_sf %>% 
  filter(site_id == "KC10" & filter_type == "3um" & line_out_depth < 31) %>% 
  select(date, line_out_depth, sf_perc) %>%
  pivot_wider(names_from = line_out_depth, values_from = sf_perc) %>% 
  select(`0m` = `0`, `5m` = `5`, `10m` = `10`, `20m` = `20`, `30m` = `30`) %>% 
  drop_na()

corr_k_3 <- round(cor(ck_3), 1)

p.mat_k_3 <- cor_pmat(ck_3)
head(p.mat_k_3[, 1:5])

#Need to set this one blank for no correlation
f5 <- ggcorrplot(corr_k_3,
           outline.color = "white",
           lab = TRUE,
           insig = "blank",
           type = "lower", 
           p.mat = p.mat_k_3,
           lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0, 1), low = "white", 
                      high =  "Red") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(color = "black"),
        legend.position = "none",
        text = element_text(size = 35))
```


```{r}
ck_g <- c_sf %>% 
  filter(site_id == "KC10" & filter_type == "GF/F" & line_out_depth < 31) %>% 
  select(date, line_out_depth, sf_perc) %>%
  pivot_wider(names_from = line_out_depth, values_from = sf_perc) %>% 
  select(`0m` = `0`, `5m` = `5`, `10m` = `10`, `20m` = `20`, `30m` = `30`) %>% 
  drop_na()

corr_k_g <- round(cor(ck_g), 1)

p.mat_k_g <- cor_pmat(ck_g)
head(p.mat_k_g[, 1:5])

f6 <- ggcorrplot(corr_k_g,
                 outline.color = "white",
           lab = TRUE,
           insig = "blank",
           type = "lower",
           p.mat = p.mat_k_g,
           lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0, 1), low = "white", 
                      high =  "Red") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.text = element_text(color = "black"),
        legend.position = "none",
        text = element_text(size = 35))

```

```{r}
fig <- (f1 + f2 + f3) / (f4 + f5 + f6)

ggsave(here("figs_invent", "correlation_percentage test.png"),
       width = 16, height = 12, dpi = 300)
```
```{r}


c_sf <- c_sf %>% 
  mutate(month = lubridate::month(date))

c_sf <- c_sf %>%
  mutate(season = case_when(month == 12 | month == 1 | month == 2 ~ "Winter",
                            month >= 3 & month <= 5 ~ "Spring",
                            month >= 6 & month <= 8 ~ "Summer",
                            month >= 9 & month <= 11 ~ "Autumn",)) %>%
  relocate(season, .after = month)    
  
#Order locations from fjord to shelf
order_loc_seas <- c("Winter", "Spring", "Summer", "Autumn")



#Chemtax - Specify order of phyto groups for figures
c_sf <- arrange(mutate(c_sf,
                         season = factor(season, levels = order_loc_seas)))


```



```{r}
c_sf %>% 
  filter(!filter_type == "2um" & line_out_depth < 31) %>%
  group_by(site_id, line_out_depth, season, filter_type) %>% 
  summarise(mean_perc = median(chla_dm)) %>% 
  ungroup() %>% 
  ggplot(aes(x = mean_perc, y = fct_rev(as_factor(line_out_depth)), fill = filter_type)) +
  geom_bar(stat = "identity", position = "stack", color = "black") +
  facet_grid(site_id~season, scales = "free_x") +
  ggsci::scale_fill_npg(name = "Filter Size") +
  labs(x = "Chla (ug/L)",
       y = "Depth (m)") +
  theme_bw() +
  theme(strip.background = element_blank(),
        text = element_text(size = 35),
        axis.text = element_text(colour = "black"),
        legend.position = c(0.18, 0.6))

ggsave(here("figs_invent", "Depth_mean_sf_median.png"), 
       width = 20, height = 12, dpi = 300)
```

```{r}
c_sf %>% 
  filter(!filter_type == "2um" & line_out_depth < 31) %>%
  group_by(site_id, line_out_depth, season, filter_type) %>% 
  summarise(mean_perc = median(chla_dm)) %>% 
  ungroup() %>% 
  ggplot(aes(x = mean_perc, y = fct_rev(as_factor(line_out_depth)), fill = filter_type)) +
  geom_bar(stat = "identity", position = "fill", color = "black") +
  facet_grid(site_id~season, scales = "free_x") +
  ggsci::scale_fill_npg(name = "Filter Size") +
  labs(x = "% Chla (ug/L)",
       y = "Depth (m)") +
  theme_bw() +
  theme(strip.background = element_blank(),
        text = element_text(size = 35),
        axis.text = element_text(colour = "black"),
        legend.position = "none")

ggsave(here("figs_invent", "Depth_mean_sf_median_perc.png"), 
       width = 20, height = 12, dpi = 300)
```


```{r}

```











```{r}
#Working on nmds
c_nmds <- c_sf_perc_wide 
# 
# #Arranging according to site ID and date
c_nmds <- c_nmds %>%
  mutate(month = lubridate::month(date)) %>%
  arrange(site_id, date) %>%
  relocate(month, .after = date)
# 
nq <- c_nmds %>%
  filter(site_id == "QU39")
# 
nk <- c_nmds %>%
  filter(site_id == "KC10" & `3um` > 0)
# 
nq_perc <- nq[, 5:ncol(nq)]

nk_perc <- nk[, 5:ncol(nk)]
# 
# nq_rel <- decostand(nq_conc, method = "total")
# 
# nq_conc_t <- log10(nq_conc + 1)
# 
# nk_conc_t <- log10(nk_conc + 1)
# 
# nq_rel_t <- sqrt(nq_rel)

```

```{r}
nk_nmds <-  metaMDS(nk_perc, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100)
# 
# 
# 
# nq_nmds_rel <-  metaMDS(nq_rel_t, distance = "bray", autotransform = FALSE,
#                          k = 2, trymax = 100) 
# 
# nk_nmds <-  metaMDS(nk_conc_t, distance = "bray", autotransform = FALSE,
#                          k = 2, trymax = 100) 
# 
# nq_nmds #0.08 - Good
# nq_nmds_rel
# nk_nmds
# 
# stressplot(nq_nmds)
```
```{r}
data.scores = as.data.frame(scores(nk_nmds))
data.scores$month = nk$month
data.scores$depth = nk$line_out_depth
# 
# data.scores_rel = as.data.frame(scores(nq_nmds_rel))
# data.scores_rel$month = nq$month
# data.scores_rel$depth = nq$line_out_depth
# 
# data.scores_k = as.data.frame(scores(nk_nmds))
# data.scores_k$month = nk$month
# data.scores_k$depth = nk$line_out_depth
```

```{r}
#Plotting nMDS - commented sections are for if I want to add environmental fits.

ggplot(data = data.scores, aes(x = NMDS1, y = NMDS2)) +
  geom_point(data = data.scores, aes(fill = as.factor(depth)),
             size = 4, pch = 21) +
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) +
  # scale_shape_manual(values = c(21, 22, 23, 24, 25)) +
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2),
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) +
  # xlim(-0.5, 1.8) +
  theme(axis.title = element_text(size = 10, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.key = element_blank(),
        legend.title = element_text(size = 10, face = "bold", colour = "black"),
        legend.text = element_text(size = 9, colour = "black"),
        legend.position = c(0.92, 0.6),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

# ggsave(here("figures_new", "nmds_micro_absolute_photo.png"),
#        width = 6, height = 4.5, dpi = 300)
```



