---
title: "2021 Chlorophyll Data Assessment"
output: html_notebook
---

This workbook quantifies how many HPLC samples were collected in 2021 - at which stations, depths and groups.

```{r}
#Load packages
library(tidyverse)  
library(readxl)
library(here)
library(patchwork)
```

```{r}
#Read data file downloaded from the portal - downloaded on 2021-10-06, so in this version does not include entire year
hplc <- read_csv(here("files", "hplc_2021_2021-11-18.csv"))

```

```{r}
#Limiting to pertinent columns
hplc <- hplc %>% 
  select(date, work_area, survey, site_id, line_out_depth)

hplc <- hplc %>% 
  mutate(year = lubridate::year(date))

```

```{r}
#Creating some summary lists to see what stations are being collected by each group

#Making a list of distinct stations and surveys
stations <- hplc %>% 
  distinct(site_id)

#Making a list of distinct surveys
surveys <- hplc %>% 
  distinct(survey)

#Making a list of distinct survey/stations matches
stations_survey <- hplc %>% 
  distinct(survey, site_id)
```

```{r}
#Classifying stations/surveys by group that collected them - trying it first on the truncated list
hplc <- hplc %>%
  mutate(group = NA) %>% 
  mutate(group = case_when(survey == "MACRO_MGEO" | survey == "ROCKY" ~ "NS",
                           survey == "ZOOPSPRINT" ~ "MFW",
                           survey == "BIOWEEKLY" ~ "Bio.",
                           survey == "TOBA" ~ "Toba",
                           survey == "QOMA1" ~ "Ocean",
                           survey == "QOMA1;ZOOPSPRINT" ~ "Ocean",
                           survey == "QOMA5" ~ "Ocean",
                           survey == "PROCESS STUDY - QCS" ~ "Process",
                           survey == "PROCESS STUDY - QCS;QCS PROCESS STUDY" ~ "Process",
                           survey == "QCS_V1" ~ "Ocean",
                           survey == "KWAK" ~ "Ocean", 
                           survey == "RVRS" ~ "Ocean",
                           survey == "BIOTIDAL" ~ "Bio.",
                           survey == "BUTE" ~ "Bute",
                           survey == "FZH,KWAK" ~ "Ocean",
                           survey == "JS1" ~ "JS",
                           survey == "JS12" ~ "JS",
                           survey == "KNIGHT" ~ "Kni.",
                           survey == "KWAK,FZH" ~ "Ocean",
                           survey == "MFW" ~ "MFW",
                           survey == "QCS_V2" ~ "Ocean",
                           survey == "QOMD" ~ "Ocean",
                           survey == "QOME" ~ "Ocean",
                           survey == "QRAFT" ~ "Ocean",
                           survey == "QRAFT1" ~ "Ocean",
                           survey == "QRAFTB" ~ "Ocean",
                           survey == "SEASTAR WASTING DISEASE,ROCKY" ~ "NS",
                           TRUE ~ as.character(group)))

#Looking at what surveys I'm missing by adding 2019 and 2020 data
na <- hplc %>% 
  filter(is.na(group)) %>% 
  distinct(survey, site_id)

```

```{r}
#Looking at depths of oceanography stations
ocean_depths <- hplc %>% 
  filter(year == "2021" & group == "Ocean" & !site_id == "QCS01") %>% 
  select(site_id, line_out_depth) %>%
  group_by(site_id, line_out_depth) %>% 
  summarise(n_filt = n()) %>% 
  ungroup() %>% 
  distinct()
```

```{r}
totals_2021 <- hplc %>% 
  filter(year == 2021) %>% 
  group_by(group) %>%
  summarize(n_tot = n()) %>% 
  ungroup()
```

```{r}
hplc %>% 
  group_by(group) %>% 
  summarise(n_filt = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(group, n_filt), y = n_filt, fill = group)) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(x = group, y = n_tot, label = n_tot, fill = NULL),
              data = totals_2021, vjust = -0.5, size = 10) +
  ggsci::scale_fill_npg() +
  ylim(0, 200) +
  ylab("# of samples") +
  ggtitle(2021) +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1),
        text = element_text(size = 35))

ggsave(here("figs_invent", "hplc_sample_numbers_by_group.png"), 
       width = 16, height = 10, dpi = 300)
```

```{r}
st_totals_2021 <- hplc %>% 
  filter(year == 2021 & group == "Ocean") %>% 
  group_by(group, site_id) %>%
  summarize(n_tot = n()) %>% 
  ungroup()
```

```{r}

hplc %>% 
  filter(group == "Ocean" & year == 2021) %>% 
  group_by(line_out_depth, site_id) %>% 
  summarise(n_dep = n()) %>% 
  ungroup() %>% 
  ggplot(aes(x = reorder(site_id, n_dep), y = n_dep, 
             fill = as.factor(line_out_depth))) +
  geom_bar(stat = "identity", color = "black") +
  geom_text(aes(x = site_id, y = n_tot, label = n_tot, fill = NULL), 
            data = st_totals_2021, vjust = -0.5, size = 10) +
  ggsci::scale_fill_npg(name = "Depth") +
  ylim(0, 200) +
  ylab("# of samples") +
  theme_bw() +
  theme(legend.position = c(0.06, 0.83),
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.4),
        text = element_text(size = 35))

ggsave(here("figs_invent", "hplc_sample_numbers_ocean.png"),
       width = 16, height = 10, dpi = 300)
```




