---
title: "R Notebook"
output: html_notebook
---



```{r}
#Load packages
library(tidyverse)  
library(readxl)
library(here)
library(patchwork)
library(ggcorrplot)
library(vegan)

```

```{r}
#Read data file downloaded from the portal - 
c <- read_csv(here("files", "qu39_kc10_dfo2_depth.csv"))

```

```{r}
#Limiting to pertinent columns
c <- c %>% 
  select(date, collected, work_area, survey, site_id, line_out_depth,
         filter_type, chla, chla_flag)

#Adding year column
c <- c %>% 
  mutate(year = lubridate::year(date))

#Only including AV and unflagged data
c_qc <- c %>% 
  filter(!is.na(chla) & (chla_flag == "AV" | chla_flag == "ADL" | is.na(chla_flag)))

#Removing exact duplicates -  not replicates. Not sure why these are happening
c_qc <- c_qc %>% 
  group_by(date, site_id, line_out_depth, filter_type) %>% 
  distinct(.keep_all = TRUE) %>% 
  ungroup()

#Calculating daily mean where there are replicates - OK for now
c_dm <- c_qc %>% 
  group_by(date, site_id, line_out_depth, filter_type) %>% 
  summarise(chla_dm = mean(chla),
            chla_sdev = sd(chla),
            n_samp = n()) %>% 
  ungroup() %>% 
  mutate_at(vars(chla_dm, chla_sdev), funs(round(., 2)))

#Separating Bulk data
c_bulk <- c_dm %>% 
  filter(filter_type == "Bulk GF/F")


#Removing bulk data
c_dm <- c_dm %>% 
  filter(!filter_type == "Bulk GF/F")



#Pivoting to calculate size-fractionated sum
c_wide <- c_dm %>%
  select(date:chla_dm) %>% 
  pivot_wider(names_from = filter_type, values_from = chla_dm) %>%
  mutate(sum = `20um` + `3um` + `GF/F`) %>% 
  select(date, site_id, line_out_depth, sum)

# %>% 
#   select(date:line_out_depth, sum)

#Bringing sum into long format (did it this way as across column sum will throw NA if not all filters present). Then, calculating the percent size fraction.

#Joining sum to long format
c_dm <- c_dm %>% 
  left_join(c_wide) %>% 
  filter(!is.na(sum)) 

#Calculating percent contribution for each filter type and limiting decimal place to 2
c_dm <- c_dm %>% 
  mutate(perc = chla_dm/sum) %>% 
  mutate_at(vars(perc), funs(round(., 2)))

#Pivoting concentrations wider to plot as scatter
cl_c <- c_dm %>%
  select(date:chla_dm) %>% 
  pivot_wider(names_from = line_out_depth, values_from = chla_dm) %>% 
  rename(m0 = `0`, m5 = `5`, m1 = `1`, m10 = `10`, m20 = `20`, m30 = `30`)

#Pivoting percentages wider to plot as scatter
cl_p <- c_dm %>%
  select(date:filter_type, perc) %>% 
  pivot_wider(names_from = line_out_depth, values_from = perc) %>% 
  rename(m0 = `0`, m5 = `5`, m1 = `1`, m10 = `10`, m20 = `20`, m30 = `30`)
  
```
```{r}
#Looking at what sampling depth usually had the peak in chlorophyll biomass.
c_max <- c_bulk %>% 
  group_by(date, site_id) %>% 
  slice_max(chla_dm) %>% 
  ungroup()

#Summarizing the number of times each depth was the max depth for each station
c_max_n <- c_max %>% 
  group_by(site_id, line_out_depth) %>% 
  summarise(n_max = n()) %>% 
  ungroup() %>% 
  group_by(site_id) %>% 
  mutate(sum = sum(n_max)) %>% 
  ungroup() %>% 
  mutate(max_perc = n_max/sum*100) %>% 
  mutate_at(vars(max_perc), funs(round(., 0)))
```


```{r}
#Trying to plot this out
f1 <- c_max_n %>% 
  ggplot(aes(x = site_id, y = n_max, fill = as.factor(line_out_depth))) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = n_max), position = position_dodge(width = 0.9),
            vjust = -0.25, size = 10) +
  ggsci::scale_fill_npg(name = "Depth") +
  ylim(0, 120) +
  ylab("# Max Chl") +
  theme_bw() +
  theme(legend.position = c(0.06, 0.75),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        text = element_text(size = 25))

f2 <- c_max_n %>% 
  ggplot(aes(x = site_id, y = max_perc, fill = as.factor(line_out_depth))) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_text(aes(label = max_perc), position = position_dodge(width = 0.9),
            vjust = 0.5, hjust = -0.2, angle = 90, size = 10) +
  ggsci::scale_fill_npg() +
  ylim(0, 60) +
  ylab("% Max Chl") +
  theme_bw() +
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        text = element_text(size = 25))

fig <- f1/f2

ggsave(here("figs_invent", "chl_max_dep.png"), fig,
       width = 13, height = 12, dpi = 300)
```



```{r}
c_dm %>% 
  filter(site_id == "QU39") %>% 
  ggplot(aes(x = date, y = log10(chla_dm), color = as.factor(line_out_depth))) +
  geom_point(size = 2) +
  geom_line(size = 2) +
  labs(y = "log10(Chl (ug/L))") +
  ggtitle("QU39") +
  ggsci::scale_color_npg(name = "Depth") +
  facet_wrap(~ filter_type, ncol = 1, scales = "free_y") +
  theme_bw() +
  theme(
        axis.title.x = element_blank(),
        text = element_text(size = 30))
  
ggsave(here("figs_invent", "TS_QU39_filt-type_CONC.png"),
       width = 16, height = 14, dpi = 300)
```
```{r}
c_dm %>% 
  filter(site_id == "QU39") %>% 
  ggplot(aes(x = date, y = perc, color = as.factor(line_out_depth))) +
  geom_point(size = 2) +
  geom_line(size = 2) +
  labs(y = "% of total") +
  ggtitle("QU39") +
  ggsci::scale_color_npg(name = "Depth") +
  facet_wrap(~ filter_type, ncol = 1, scales = "free_y") +
  theme_bw() +
  theme(
        axis.title.x = element_blank(),
        text = element_text(size = 30))
  
ggsave(here("figs_invent", "TS_QU39-filt-type_PERC.png"),
       width = 16, height = 14, dpi = 300)
```

```{r}
c_dm %>% 
  filter(site_id == "DFO2") %>% 
  ggplot(aes(x = date, y = log10(chla_dm), color = as.factor(line_out_depth))) +
  geom_point(size = 2) +
  geom_line(size = 2) +
  labs(y = "log10(Chl (ug/L))") +
  ggtitle("DFO2") +
  ggsci::scale_color_npg(name = "Depth") +
  facet_wrap(~ filter_type, ncol = 1, scales = "free_y") +
  theme_bw() +
  theme(
        axis.title.x = element_blank(),
        text = element_text(size = 30))
  
ggsave(here("figs_invent", "TS_DFO2_filt_type_CONC.png"),
       width = 16, height = 14, dpi = 300)
```

```{r}

c_dm %>% 
  filter(site_id == "DFO2") %>% 
  ggplot(aes(x = date, y = perc, color = as.factor(line_out_depth))) +
  geom_point(size = 2) +
  geom_line(size = 2) +
  labs(y = "% of total") +
  ggtitle("DFO2") +
  ggsci::scale_color_npg(name = "Depth") +
  facet_wrap(~ filter_type, ncol = 1, scales = "free_y") +
  theme_bw() +
  theme(
        axis.title.x = element_blank(),
        text = element_text(size = 30))
  
ggsave(here("figs_invent", "TS_DFO2_filt-type_PERC.png"),
       width = 16, height = 14, dpi = 300)
```

```{r}
c_dm %>% 
  filter(site_id == "KC10" & date > "2017-01-01") %>% 
  ggplot(aes(x = date, y = log10(chla_dm), color = as.factor(line_out_depth))) +
  geom_point(size = 2) +
  geom_line(size = 2) +
  labs(y = "log10(Chl (ug/L))") +
  ggtitle("KC10") +
  ggsci::scale_color_npg(name = "Depth") +
  facet_wrap(~ filter_type, ncol = 1, scales = "free_y") +
  theme_bw() +
  theme(
        axis.title.x = element_blank(),
        text = element_text(size = 30))
  
ggsave(here("figs_invent", "TS_KC10-filt-type_CONC.png"),
       width = 16, height = 14, dpi = 300)
```
```{r}
c_dm %>% 
  filter(site_id == "KC10" & date > "2017-01-01") %>% 
  ggplot(aes(x = date, y = perc, color = as.factor(line_out_depth))) +
  geom_point(size = 2) +
  geom_line(size = 2) +
  labs(y = "% of total") +
  ggtitle("KC10") +
  ggsci::scale_color_npg(name = "Depth") +
  facet_wrap(~ filter_type, ncol = 1, scales = "free_y") +
  theme_bw() +
  theme(
        axis.title.x = element_blank(),
        text = element_text(size = 30))
  
ggsave(here("figs_invent", "TS_KC10-filt-type_PERC.png"),
       width = 16, height = 14, dpi = 300)
```

```{r}
cq_20 <- cl_p %>% 
  filter(site_id == "QU39" & filter_type == "20um") %>% 
  select(`0m` = m0, `5m` = m5, `10m` = m10, `20m` = m20, `30m` =  m30) %>% 
  drop_na()

corr_q_20 <- round(cor(cq_20), 1)

p.mat_q_20 <- cor_pmat(cq_20)
head(p.mat_q_20[, 1:5])

f1 <- ggcorrplot(corr_q_20, outline.color = "white", lab = TRUE, type = "lower", 
           p.mat = p.mat_q_20, lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0.3, 1), low = "white", 
                      high =  "red") +
  ggtitle("20um") +
  annotate("text", x = 1, y = 4.3, label = "QU39", size = 10) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = c(0.15, 0.67),
        text = element_text(size = 30))

cq_3 <- cl_p %>% 
  filter(site_id == "QU39" & filter_type == "3um") %>% 
  select(`0m` = m0, `5m` = m5, `10m` = m10, `20m` = m20, `30m` =  m30) %>% 
  drop_na()

corr_q_3 <- round(cor(cq_3), 1)

p.mat_q_3 <- cor_pmat(cq_3)
head(p.mat_q_3[, 1:5])

f2 <- ggcorrplot(corr_q_3, outline.color = "white", lab = TRUE, type = "lower", 
           p.mat = p.mat_q_3, lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0.3, 1), low = "white", 
                      high =  "red") +
  ggtitle("3um") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

cq_g <- cl_p %>% 
  filter(site_id == "QU39" & filter_type == "GF/F") %>% 
  select(`0m` = m0, `5m` = m5, `10m` = m10, `20m` = m20, `30m` =  m30) %>% 
  drop_na()

corr_q_g <- round(cor(cq_g), 1)

p.mat_q_g <- cor_pmat(cq_g)
head(p.mat_q_g[, 1:5])

f3 <- ggcorrplot(corr_q_g, outline.color = "white", lab = TRUE, type = "lower", 
           p.mat = p.mat_q_g, lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0.3, 1), low = "white", 
                      high =  "red") +
  ggtitle("GF/F") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

ck_20 <- cl_p %>% 
  filter(site_id == "KC10" & filter_type == "20um") %>% 
  select(`0m` = m0, `5m` = m5, `10m` = m10, `20m` = m20, `30m` =  m30) %>% 
  drop_na()

corr_k_20 <- round(cor(ck_20), 1)

p.mat_k_20 <- cor_pmat(ck_20)
head(p.mat_k_20[, 1:5])

f4 <- ggcorrplot(corr_k_20, outline.color = "white", lab = TRUE, type = "lower", 
           p.mat = p.mat_k_20, lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0.3, 1), low = "white", 
                      high =  "red") +
  annotate("text", x = 1, y = 4.3, label = "KC10", size = 10) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

ck_3 <- cl_p %>% 
  filter(site_id == "KC10" & filter_type == "3um") %>% 
  select(`0m` = m0, `5m` = m5, `10m` = m10, `20m` = m20, `30m` =  m30) %>% 
  drop_na()

corr_k_3 <- round(cor(ck_3), 1)

p.mat_k_3 <- cor_pmat(ck_3)
head(p.mat_k_3[, 1:5])

#Need to set this one blank for no correlation
f5 <- ggcorrplot(corr_k_3, outline.color = "white", lab = TRUE, type = "lower", 
           p.mat = p.mat_k_3, insig = "blank", lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0.3, 1), low = "white", 
                      high =  "red") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

ck_g <- cl_p %>% 
  filter(site_id == "KC10" & filter_type == "GF/F") %>% 
  select(`0m` = m0, `5m` = m5, `10m` = m10, `20m` = m20, `30m` =  m30) %>% 
  drop_na()

corr_k_g <- round(cor(ck_g), 1)

p.mat_k_g <- cor_pmat(ck_g)
head(p.mat_k_g[, 1:5])

f6 <- ggcorrplot(corr_k_g, outline.color = "white", lab = TRUE, type = "lower", 
           p.mat = p.mat_k_g, lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0.3, 1), low = "white", 
                      high =  "red") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

cd_20 <- cl_p %>% 
  filter(site_id == "DFO2" & filter_type == "20um") %>% 
  select(`0m` = m0, `5m` = m5, `10m` = m10, `20m` = m20, `30m` =  m30) %>% 
  drop_na()

corr_d_20 <- round(cor(cd_20), 1)

p.mat_d_20 <- cor_pmat(cd_20)
head(p.mat_d_20[, 1:5])

f7 <- ggcorrplot(corr_d_20, outline.color = "white", lab = TRUE, type = "lower", 
           p.mat = p.mat_d_20, insig = "blank", lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0.3, 1), low = "white", 
                      high =  "red") +
  annotate("text", x = 1, y = 4.3, label = "DFO2", size = 10) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

cd_3 <- cl_p %>% 
  filter(site_id == "DFO2" & filter_type == "3um") %>% 
  select(`0m` = m0, `5m` = m5, `10m` = m10, `20m` = m20, `30m` =  m30) %>% 
  drop_na()

corr_d_3 <- round(cor(cd_3), 1)

p.mat_d_3 <- cor_pmat(cd_3)
head(p.mat_d_3[, 1:5])

#Need to set this one blank for no correlation
f8 <- ggcorrplot(corr_d_3, outline.color = "white", lab = TRUE, type = "lower", 
           p.mat = p.mat_d_3, insig = "blank", lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0.3, 1), low = "white", 
                      high =  "red") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

cd_g <- cl_p %>% 
  filter(site_id == "DFO2" & filter_type == "GF/F") %>% 
  select(`0m` = m0, `5m` = m5, `10m` = m10, `20m` = m20, `30m` =  m30) %>% 
  drop_na()

corr_d_g <- round(cor(cd_g), 1)

p.mat_d_g <- cor_pmat(cd_g)
head(p.mat_d_g[, 1:5])

f9 <- ggcorrplot(corr_d_g, outline.color = "white", lab = TRUE, type = "lower", 
           p.mat = p.mat_d_g, lab_size = 10) +
  scale_fill_gradient(name = "R", limit = c(0.3, 1), low = "white", 
                      high =  "red") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        legend.position = "none",
        text = element_text(size = 30))

fig <- (f1 + f2 + f3) / (f4 + f5 + f6) / (f7 + f8 + f9)

ggsave(here("figs_invent", "correlation_test.png"),
       width = 16, height = 16, dpi = 300)
```

```{r}
#Working on nmds
c_nmds <- c_dm %>%
  select(date:chla_dm) %>% 
  pivot_wider(names_from = filter_type, values_from = chla_dm)

#Arranging according to site ID and date
c_nmds <- c_nmds %>% 
  mutate(month = lubridate::month(date)) %>% 
  arrange(site_id, date) %>% 
  relocate(month, .after = date)

nq <- c_nmds %>% 
  filter(site_id == "QU39")

nk <- c_nmds %>% 
  filter(site_id == "KC10" & `3um` > 0)  

nq_conc <- nq[, 5:ncol(nq)]

nk_conc <- nk[, 5:ncol(nk)]

nq_rel <- decostand(nq_conc, method = "total")

nq_conc_t <- log10(nq_conc + 1)

nk_conc_t <- log10(nk_conc + 1)

nq_rel_t <- sqrt(nq_rel)

```

```{r}
nq_nmds <-  metaMDS(nq_conc_t, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 



nq_nmds_rel <-  metaMDS(nq_rel_t, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

nk_nmds <-  metaMDS(nk_conc_t, distance = "bray", autotransform = FALSE,
                         k = 2, trymax = 100) 

nq_nmds #0.08 - Good
nq_nmds_rel
nk_nmds

stressplot(nq_nmds)
```
```{r}
data.scores = as.data.frame(scores(nq_nmds))
data.scores$month = nq$month
data.scores$depth = nq$line_out_depth

data.scores_rel = as.data.frame(scores(nq_nmds_rel))
data.scores_rel$month = nq$month
data.scores_rel$depth = nq$line_out_depth

data.scores_k = as.data.frame(scores(nk_nmds))
data.scores_k$month = nk$month
data.scores_k$depth = nk$line_out_depth
```

```{r}
#Plotting nMDS - commented sections are for if I want to add environmental fits.

ggplot(data = data.scores_k, aes(x = NMDS1, y = NMDS2)) + 
  geom_point(data = data.scores_k, aes(fill = as.factor(month), shape = as.factor(depth)),
             size = 4) + 
  scale_fill_brewer(palette = "RdYlBu") +
  # scale_fill_manual(values = c("blue", "springgreen4", "black", "magenta")) + 
  scale_shape_manual(values = c(21, 22, 23, 24, 25)) + 
  # geom_segment(aes(x = 0, y = 0, xend = NMDS1, yend = NMDS2), 
  #              data = en_coord_cont, size = 1, alpha = 0.5, colour = "grey30") +
  # geom_text(data = en_coord_cont, aes(x = NMDS1, y = NMDS2), colour = "grey30",
  #           fontface = "bold", label = row.names(en_coord_cont)) + 
  # xlim(-0.5, 1.8) +
  theme(axis.title = element_text(size = 10, face = "bold", colour = "black"),
        panel.background = element_blank(),
        panel.border = element_rect(fill = NA, colour = "black"), 
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        legend.key = element_blank(), 
        legend.title = element_text(size = 10, face = "bold", colour = "black"), 
        legend.text = element_text(size = 9, colour = "black"),
        legend.position = c(0.92, 0.6),
        legend.margin = margin(-0.3,0,0,0, unit = "cm"),
        text = element_text(size = 30)) +
  labs(fill = "Month", shape = "Station") +
  guides(fill = guide_legend(override.aes = list(shape = 21)))

# ggsave(here("figures_new", "nmds_micro_absolute_photo.png"),
#        width = 6, height = 4.5, dpi = 300)
```

```{r}
cl_p %>% 
  filter(site_id == "DFO2" & filter_type == "3um") %>% 
  ggplot(aes(x = m20, y = m30)) +
  geom_point() +
  lims(x = c(0, 1),
       y = c(0, 1))
```

